spring:
  kafka:
    bootstrap-servers: ${app.kafka.host}:${app.kafka.port}

app:
  topic:
    foo: my-topic

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG