spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.jarranzz.svc:9092

app:
  topic:
    foo: my-topic

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG